/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vs.code.test;

import org.apache.commons.lang3.StringUtils;

public class App {

    public String getGreeting() {
        var str = "aaabbb";
        str = StringUtils.upperCase(str);
        return "Hello " + str;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
